name: Deploy Django to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH agent and add key
      run: |
        mkdir -p ~/.ssh  # .sshディレクトリを作成
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa <<< "${{ secrets.SSH_PASSPHRASE }}"
        ssh-keyscan -H 118.27.2.129 >> ~/.ssh/known_hosts

    - name: Upload Django files to server
      run: |
        scp -v -r ./* root@118.27.2.129:/root/rest

    - name: SSH and restart Gunicorn
      run: |
        ssh root@118.27.2.129 << 'EOF'
          source /root/rest/activate
          python manage.py migrate
          sudo systemctl restart gunicorn
        EOF
