name: Deploy Django to VPS

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときにトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > root/.ssh/id_rsa
        chmod 600 root/.ssh/id_rsa
        ssh-keyscan -H 118.27.2.129 >> root/.ssh/known_hosts

    - name: Upload Django files to server
      run: |
        scp -r ./* root@118.27.2.129:/root/rest

    - name: SSH and restart Gunicorn
      run: |
        ssh root@118.27.2.129 << 'EOF'
          source /root/rest/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
        EOF
