name: Deploy Django to VPS

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときにトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウト
      uses: actions/checkout@v2

    - name: サーバーにファイルをアップロード
      uses: appleboy/scp-action@v0.1.3
      with:
        host: 118.27.2.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        source: "./*"
        target: "/root/rest"

    - name: サーバーでコマンドを実行
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: 118.27.2.129
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: 22
        script: |
          source /root/rest/activate
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
